// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrvwebwwzjwqomgfeydt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFydndlYnd3emp3cW9tZ2ZleWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NTU3NTYsImV4cCI6MjA4NTQzMTc1Nn0.fCH3klArhVieIGLYWsxxf0Nx6Urx_J6QshrkBXkmvhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});